In [ ]:
import pandas as pd
import numpy as np

data = {
    'patient_id': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
                   111, 112, 113, 114, 115, 101, 107, 118, 119, 120],
    'age': ['25', '34', None, '45', '29', None, '38', '52', '27', '41',
            '33', 'unknown', '48', '26', '35', '25', '38', '31', None, '44'],
    'weight': ['70', '65', '80', None, '75', None, '68', '90', '72', '85',
               '78', None, '82', '69', 'N/A', '70', '68', '74', None, '88'],
    'blood_pressure': [120, 130, None, 140, 125, None, 135, None, 118, 145,
                      128, None, 138, 122, None, 120, 135, 126, None, 142],
    'medication': ['Aspirin', 'Metformin', 'Lisinopril', None, 'Aspirin',
                   'Metformin', 'Lisinopril', 'Aspirin', None, 'Metformin',
                   'Lisinopril', 'Aspirin', None, 'Metformin', 'Aspirin',
                   'Aspirin', 'Lisinopril', 'Metformin', 'Aspirin', None],
    'insurance_provider': ['Blue Cross', 'Aetna', 'Cigna', 'UnitedHealth', None,
                          'Blue Cross', 'Aetna', 'Cigna', 'UnitedHealth', 'Blue Cross',
                          'Aetna', None, 'UnitedHealth', 'Blue Cross', 'Aetna',
                          'Blue Cross', 'Aetna', 'Cigna', 'UnitedHealth', None]
}

df = pd.DataFrame(data)

# Task 1: Inspect the Data

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   patient_id          20 non-null     int64
 1   age                 17 non-null     object
 2   weight              16 non-null     object
 3   blood_pressure      14 non-null     float64
 4   medication          16 non-null     object
 5   insurance_provider  17 non-null     object
dtypes: float64(1), int64(1), object(4)
memory usage: 1.1+ KB

In [ ]:
df.isnull().sum()

patient_id            0
age                   3
weight                4
blood_pressure        6
medication            4
insurance_provider    3
dtype: int64

In [ ]:
(df.isnull().sum()/len(df))*100

patient_id             0.0
age                   15.0
weight                20.0
blood_pressure        30.0
medication            20.0
insurance_provider    15.0
dtype: float64

In [ ]:
df.duplicated().sum()

np.int64(2)

# Task 2: Data Type Conversion

In [ ]:
df['age']=pd.to_numeric(df['age'], errors='coerce')

In [ ]:
df['weight']=pd.to_numeric(df['weight'], errors='coerce')

In [ ]:
df.isnull().sum()

patient_id            0
age                   4
weight                5
blood_pressure        6
medication            4
insurance_provider    3
dtype: int64

In [ ]:
df['insurance_provider'] = df['insurance_provider'].astype('category')

In [ ]:
df.dtypes

patient_id               int64
age                    float64
weight                 float64
blood_pressure         float64
medication              object
insurance_provider    category
dtype: object

# Task 3: Handling missing values

In [ ]:
df['age'] = df['age'].fillna(df['age'].median())

In [ ]:
df['weight'] = df['weight'].fillna(df['weight'].median())

In [ ]:
df['blood_pressure'] = df['blood_pressure'].fillna(df['blood_pressure'].median())

In [ ]:
df['medication'] = df['medication'].fillna(df['medication'].mode()[0])

In [ ]:
df['insurance_provider'] = df['insurance_provider'].cat.add_categories('Unknown')
df['insurance_provider'] = df['insurance_provider'].fillna('Unknown')

In [ ]:
df.isnull().sum()

patient_id            0
age                   0
weight                0
blood_pressure        0
medication            0
insurance_provider    0
dtype: int64

# Task 4:Handle Duplicates

In [ ]:
df[df.duplicated(keep=False)]

    patient_id   age  weight  blood_pressure  medication insurance_provider
0          101  25.0    70.0           120.0     Aspirin         Blue Cross
6          107  38.0    68.0           135.0  Lisinopril              Aetna
15         101  25.0    70.0           120.0     Aspirin         Blue Cross
16         107  38.0    68.0           135.0  Lisinopril              Aetna

In [ ]:
df.duplicated(subset=['patient_id'])

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15     True
16     True
17    False
18    False
19    False
dtype: bool

In [ ]:
df.duplicated(subset=['patient_id']).sum()

np.int64(2)

In [ ]:
df.shape

(20, 6)

In [ ]:
df1 = df.drop_duplicates(subset=['patient_id'], keep='first')

In [ ]:
df1.shape

(18, 6)

# Task 5: Complete Workflow with Verification

In [ ]:
import pandas as pd
import numpy as np

data = {
    'patient_id': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
                   111, 112, 113, 114, 115, 101, 107, 118, 119, 120],
    'age': ['25', '34', None, '45', '29', None, '38', '52', '27', '41',
            '33', 'unknown', '48', '26', '35', '25', '38', '31', None, '44'],
    'weight': ['70', '65', '80', None, '75', None, '68', '90', '72', '85',
               '78', None, '82', '69', 'N/A', '70', '68', '74', None, '88'],
    'blood_pressure': [120, 130, None, 140, 125, None, 135, None, 118, 145,
                      128, None, 138, 122, None, 120, 135, 126, None, 142],
    'medication': ['Aspirin', 'Metformin', 'Lisinopril', None, 'Aspirin',
                   'Metformin', 'Lisinopril', 'Aspirin', None, 'Metformin',
                   'Lisinopril', 'Aspirin', None, 'Metformin', 'Aspirin',
                   'Aspirin', 'Lisinopril', 'Metformin', 'Aspirin', None],
    'insurance_provider': ['Blue Cross', 'Aetna', 'Cigna', 'UnitedHealth', None,
                          'Blue Cross', 'Aetna', 'Cigna', 'UnitedHealth', 'Blue Cross',
                          'Aetna', None, 'UnitedHealth', 'Blue Cross', 'Aetna',
                          'Blue Cross', 'Aetna', 'Cigna', 'UnitedHealth', None]
}

df = pd.DataFrame(data)

In [ ]:
df_clean = df.copy()

In [ ]:
shape_before        = df_clean.shape
missing_before      = df_clean.isnull().sum()
duplicates_before   = df_clean.duplicated(subset=['patient_id']).sum()
dtypes_before       = df_clean.dtypes.copy()

# handling data types

In [ ]:
df_clean.dtypes

patient_id              int64
age                    object
weight                 object
blood_pressure        float64
medication             object
insurance_provider     object
dtype: object

In [ ]:
df_clean['age'] = pd.to_numeric(df_clean['age'], errors='coerce')
df_clean['weight'] = pd.to_numeric(df_clean['weight'], errors='coerce')
df_clean['blood_pressure'] = pd.to_numeric(df_clean['blood_pressure'], errors='coerce')
df_clean['insurance_provider'] = df_clean['insurance_provider'].astype('category')

In [ ]:
df_clean.dtypes

patient_id               int64
age                    float64
weight                 float64
blood_pressure         float64
medication              object
insurance_provider    category
dtype: object

# handling missing values

In [ ]:
df_clean.isnull().sum()

patient_id            0
age                   4
weight                5
blood_pressure        6
medication            4
insurance_provider    3
dtype: int64

In [ ]:
df_clean['age'] = df_clean['age'].fillna(df_clean['age'].median())
df_clean['weight'] = df_clean['weight'].fillna(df_clean['weight'].median())
df_clean['blood_pressure'] = df_clean['blood_pressure'].fillna(df_clean['blood_pressure'].median())
df_clean['medication'] = df_clean['medication'].fillna(df_clean['medication'].mode()[0])
df_clean['insurance_provider'] = df_clean['insurance_provider'].cat.add_categories('Unknown')
df_clean['insurance_provider'] = df_clean['insurance_provider'].fillna('Unknown')

In [ ]:
df_clean.isnull().sum()

patient_id            0
age                   0
weight                0
blood_pressure        0
medication            0
insurance_provider    0
dtype: int64

# handling duplicates

In [ ]:
df_clean.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15     True
16     True
17    False
18    False
19    False
dtype: bool

In [ ]:
df_clean.duplicated().sum()

np.int64(2)

In [ ]:
df_clean = df_clean.drop_duplicates(subset=['patient_id'], keep='first')

In [ ]:
df_clean.duplicated().sum()

np.int64(0)

In [ ]:
shape_after       = df_clean.shape
missing_after     = df_clean.isnull().sum()
duplicates_after  = df_clean.duplicated(subset=['patient_id']).sum()
dtypes_after      = df_clean.dtypes.copy()

In [ ]:
print("\tDATA CLEANING VERIFICATION REPORT")

print("\n[ Shape ]")
print(f"  Before : {shape_before}")
print(f"  After  : {shape_after}")
print(f"  Rows removed : {shape_before[0] - shape_after[0]}")

print("\n[ Missing Values ]")
print(f"  {'Column':<22} {'Before':>8} {'After':>8}")
print(f"  {'-'*40}")
for col in df.columns:
    b = missing_before[col]
    a = missing_after[col]
    status = 'fixed' if b > 0 and a == 0 else ''
    print(f"  {col:<22} {b:>8} {a:>8}   {status}")

print("\n[ Duplicates (by patient_id) ]")
print(f"  Before : {duplicates_before}")
print(f"  After  : {duplicates_after}")

print("\n[ Data Types ]")
print(f"  {'Column':<22} {'Before':>12} {'After':>12}")
print(f"  {'-'*48}")
for col in df.columns:
    print(f"  {col:<22} {str(dtypes_before[col]):>12} {str(dtypes_after[col]):>12}")

	DATA CLEANING VERIFICATION REPORT

[ Shape ]
  Before : (20, 6)
  After  : (18, 6)
  Rows removed : 2

[ Missing Values ]
  Column                   Before    After
  ----------------------------------------
  patient_id                    0        0
  age                           3        0   fixed
  weight                        4        0   fixed
  blood_pressure                6        0   fixed
  medication                    4        0   fixed
  insurance_provider            3        0   fixed

[ Duplicates (by patient_id) ]
  Before : 2
  After  : 0

[ Data Types ]
  Column                       Before        After
  ------------------------------------------------
  patient_id                    int64        int64
  age                          object      float64
  weight                       object      float64
  blood_pressure              float64      float64
  medication                   object       object
  insurance_provider           object     category